services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: example
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
  redis:
    image: 'redis:latest'
    ports:
      - "6379:6379"
    depends_on:
      - mysql
  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - '8001:8001'
    volumes:
      - ./data/redisinsight:/db
    depends_on:
      - redis